#--- General Configuration ---

# https://github.com/neovim/neovim/issues/5096
set -g default-terminal 'tmux-256color' # replace this with your custom term-info name
set -ga terminal-overrides ',*:Tc' # this is for 256 color
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q' # this is for the cursor shape

# enable mouse
setw -g mouse on

# use fish
set-option -g default-shell "/usr/bin/fish"


# --- Key Bindings ---

setw -g xterm-keys on

bind -n S-Up set-option -g status
bind -n S-Down set-option -g status
bind -n S-Left previous-window
bind -n S-Right next-window

bind -n C-S-Up new-window
bind -n C-left swap-window -t -1
bind -n C-right swap-window -t +1

bind h split-window -h
bind v split-window -v


#--- Status Bar ---

set -g status-position bottom

set -g status-fg white
set -g status-bg default

setw -g window-status-style fg=colour245,bg=default
setw -g window-status-current-style fg=colour167,bg=default

set -g status-left " "
set -g status-justify left
setw -g window-status-format         ' #(echo "#{pane_current_command}") '
setw -g window-status-current-format ' #(echo "#{pane_current_command}") '
set -g status-right " "


#--- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @yank_selection_mouse 'clipboard'

# Keep this at the end of the file
run -b '$HOME/.tmux/plugins/tpm/tpm'
