#!/usr/bin/env bash

bspc monitor -d I II III IV

bspc config border_width         4
bspc config window_gap           24
bspc config top_padding          64
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Electron state=floating rectangle=2160x1350+0+0
bspc rule -a Gnome-control-center state=floating

source $XDG_CONFIG_HOME/utilities/colors

bspc config normal_border_color $background
bspc config focused_border_color $foreground
bspc config active_border_color $foreground
bspc config urgent_border_color $color9
bspc config presel_feedback_color $foreground

sxhkd &

$XDG_CONFIG_HOME/utilities/autostart &
