config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_polybar:
    dst: ~/.config/polybar
    src: config/polybar
  d_rofi:
    dst: ~/.config/rofi
    src: config/rofi
  d_utilities:
    dst: ~/.config/utilities
    src: config/utilities
  f_bspwmrc:
    dst: ~/.config/bspwm/bspwmrc
    src: config/bspwm/bspwmrc
  f_compton.conf:
    dst: ~/.config/compton/compton.conf
    src: config/compton/compton.conf
  f_config.fish:
    dst: ~/.config/fish/config.fish
    src: config/fish/config.fish
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_hyper.js:
    dst: ~/.config/hyper/.hyper.js
    src: config/hyper/.hyper.js
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_profile:
    dst: ~/.profile
    src: profile
  f_sxhkdrc:
    dst: ~/.config/sxhkd/sxhkdrc
    src: config/sxhkd/sxhkdrc
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_xbindkeysrc:
    dst: ~/.Xbindkeysrc
    src: Xbindkeysrc
  f_xmodmap:
    dst: ~/.Xmodmap
    src: Xmodmap
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_xscreensaver:
    dst: ~/.xscreensaver
    src: xscreensaver
  f_xsession:
    dst: ~/.xsession
    src: xsession
profiles:
  Paysons-MacBook-Pro:
    dotfiles:
    - d_polybar
    - d_rofi
    - d_utilities
    - f_bspwmrc
    - f_compton.conf
    - f_config.fish
    - f_dunstrc
    - f_hyper.js
    - f_profile
    - f_sxhkdrc
    - f_xbindkeysrc
    - f_xmodmap
    - f_xresources
    - f_xscreensaver
    - f_xsession
    - f_tmux.conf
    - f_init.vim
