#!/usr/bin/env python

from pytooth import bluetooth_manager, exceptions


def main():
    manager = bluetooth_manager.BluetoothManager()

    try:
        connected = manager.get_connected_devices()

        if len(connected):
            print("")
        else:
            print("")
    except exceptions.DBusException:
        print("")


if __name__ == "__main__":
    main()
