#!/usr/bin/env bash

# Redshift
redshift &

# Background
feh --bg-scale /usr/share/backgrounds/current &

# Shadows
compton --config $XDG_CONFIG_HOME/compton/compton.conf &

# Remap modifier keys
xmodmap $HOME/.Xmodmap &

# Key repeat
xset r rate 250 20 &

# Polybar
polybar -c $XDG_CONFIG_HOME/polybar/config bar &

# Clipboard
clipster -d &

# Screensaver
xscreensaver -no-splash &
